name: 'ApiCov'
description: 'Collect API coverage data from C/C++ projects'
author: 'Code SA'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  install_path:
    description: 'The directory where the build is installed'
    required: true
  root_path:
    description: 'The directory where the repo is cloned'
    required: true

runs:
  using: "composite"
  steps:
    - name: Detect Ubuntu version
      id: detect_ubuntu
      run: |
        if [[ "$(lsb_release -rs)" == "22.04" ]]; then
          echo "version=ubuntu-22.04" >> $GITHUB_OUTPUT
        else
          echo "version=ubuntu-24.04" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Run APICov
      run: ${GITHUB_ACTION_PATH}/dist-${{ steps.detect_ubuntu.outputs.version }}/run.sh "${{ inputs.root_path }}" "${{ inputs.install_path }}"
      shell: bash
    # - name: Debug directory
    #   run: |
    #     ls -la ${{ inputs.root_path }}
    #   shell: bash
    # - name: Debug directory
    #   run: |
    #     ls -la ${{ inputs.install_path }}
    #   shell: bash    
    - name: "Upload JSON files"
      uses: actions/upload-artifact@v4
      with:
        name: api-coverage
        path: |
          ${{inputs.root_path}}/apis.json
          ${{inputs.root_path}}/api_coverage.json
        if-no-files-found: error


