[project]
name = "apicov"
version = "0.2.0"
description = "Api coverage Collector"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.13.0",
    "pytest>=8.3.5",
    "ruff>=0.11.10",
]
